version: '2'
services:
  web:
    container_name: olxtest_web
    build:
      context: .
      dockerfile: "docker/Dockerfile.web"
    links:
      - db
    ports: 
      - "8081:80"
    volumes:
      - .:/var/www/html
  db:
    container_name: olxtest_db
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: test
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d

