version: '2'

volumes:
  data:
    driver: local
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.web"
    links:
      - db
    ports: 
      - "8081:80"
    volumes:
      - data
  db:
    build:
      context: .
      dockerfile: "Dockerfile.db"
    ports:
      - "3307:3306"
    volumes:
      - data:/tmp:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: test
